Initial import

diff --git a/elfutils-0.170-dts.patch b/elfutils-0.170-dts.patch
--- a/elfutils-0.170-dts.patch
+++ b/elfutils-0.170-dts.patch
@@ -1,8 +1,8 @@
 diff --git a/backends/Makefile.am b/backends/Makefile.am
-index ff80a82..96004dc 100644
+index 37dc2d2..03b9d20 100644
 --- a/backends/Makefile.am
 +++ b/backends/Makefile.am
-@@ -41,11 +41,37 @@ libebl_pic = libebl_i386_pic.a libebl_sh_pic.a libebl_x86_64_pic.a    \
+@@ -41,12 +41,38 @@ libebl_pic = libebl_i386_pic.a libebl_sh_pic.a libebl_x86_64_pic.a    \
  	     libebl_m68k_pic.a libebl_bpf_pic.a
  noinst_LIBRARIES = $(libebl_pic)
  noinst_DATA = $(libebl_pic:_pic.a=.so)
@@ -11,6 +11,7 @@ index ff80a82..96004dc 100644
  
  libelf = ../libelf/libelf.so
  libdw = ../libdw/libdw.so
+ libeu = ../lib/libeu.a
  
 +# The following is minimal set of backends that we link with libdw to
 +# avoid dlopen. Note repeats files below because some backends reuse
@@ -41,7 +42,7 @@ index ff80a82..96004dc 100644
  	    i386_retval.c i386_regs.c i386_auxv.c i386_syscall.c \
  	    i386_initreg.c i386_unwind.c
 diff --git a/configure.ac b/configure.ac
-index c2c1d90..cc0cc62 100644
+index 1f1856d..0ca9ae2 100644
 --- a/configure.ac
 +++ b/configure.ac
 @@ -25,6 +25,12 @@ m4_ifndef([AC_PACKAGE_URL],
@@ -58,7 +59,7 @@ index c2c1d90..cc0cc62 100644
  # But if the user explicitly provided --program-prefix="" then pretend
  # it wasn't set at all (NONE). We want to test this really early before
 diff --git a/libasm/Makefile.am b/libasm/Makefile.am
-index 8094b05..b15ee55 100644
+index 9effa6c..0e10150 100644
 --- a/libasm/Makefile.am
 +++ b/libasm/Makefile.am
 @@ -38,6 +38,7 @@ noinst_LIBRARIES = libasm_pic.a
@@ -70,7 +71,7 @@ index 8094b05..b15ee55 100644
  		   asm_getelf.c asm_newscn.c asm_newscn_ingrp.c \
  		   asm_newsubscn.c asm_newsym.c asm_newcomsym.c \
 diff --git a/libcpu/Makefile.am b/libcpu/Makefile.am
-index 31fc906..33c30a9 100644
+index 94de56e..d16ba69 100644
 --- a/libcpu/Makefile.am
 +++ b/libcpu/Makefile.am
 @@ -36,9 +36,11 @@ LEX_OUTPUT_ROOT = lex.$(<F:lex.l=)
@@ -85,17 +86,17 @@ index 31fc906..33c30a9 100644
  
  i386_gendis_SOURCES = i386_gendis.c i386_lex.l i386_parse.y
  
-@@ -49,6 +51,8 @@ if HAVE_LINUX_BPF_H
+@@ -48,6 +50,8 @@ x86_64_disasm.o: x86_64.mnemonics $(srcdir)/x86_64_dis.h
  noinst_LIBRARIES += libcpu_bpf.a
  libcpu_bpf_a_SOURCES = bpf_disasm.c
  libcpu_bpf_a_CFLAGS = $(AM_CFLAGS) -Wno-format-nonliteral
 +libcpu_static_pic_a_SOURCES += $(libcpu_bpf_a_SOURCES)
 +bpf_disasm_CFLAGS = -fPIC -Wno-format-nonliteral
- endif
  
  %_defs: $(srcdir)/defs/i386
+ 	$(AM_V_GEN)m4 -D$* -DDISASSEMBLER $< > $@T
 diff --git a/libdw/Makefile.am b/libdw/Makefile.am
-index 082d96c..4cb3671 100644
+index ff8c291..b3e781d 100644
 --- a/libdw/Makefile.am
 +++ b/libdw/Makefile.am
 @@ -35,12 +35,13 @@ AM_CPPFLAGS += -I$(srcdir)/../libelf
@@ -114,9 +115,9 @@ index 082d96c..4cb3671 100644
  libdw_a_SOURCES = dwarf_begin.c dwarf_begin_elf.c dwarf_end.c dwarf_getelf.c \
  		  dwarf_getpubnames.c dwarf_getabbrev.c dwarf_tag.c \
  		  dwarf_error.c dwarf_nextcu.c dwarf_diename.c dwarf_offdie.c \
-@@ -91,6 +92,20 @@ libdw_a_SOURCES = dwarf_begin.c dwarf_begin_elf.c dwarf_end.c dwarf_getelf.c \
+@@ -91,6 +92,21 @@ libdw_a_SOURCES = dwarf_begin.c dwarf_begin_elf.c dwarf_end.c dwarf_getelf.c \
  		  dwarf_getalt.c dwarf_setalt.c dwarf_cu_getdwarf.c \
- 		  dwarf_cu_die.c dwarf_peel_type.c
+ 		  dwarf_cu_die.c dwarf_peel_type.c dwarf_default_lower_bound.c
  
 +# Minimal library with symbols needed by those libebl backends that we
 +# ship statically.  This is so that e.g. strip doesn't end up bringing
@@ -130,25 +131,26 @@ index 082d96c..4cb3671 100644
 +		dwarf_hasattr_integrate.c dwarf_hasattr.c \
 +		dwarf_aggregate_size.c dwarf_siblingof.c dwarf_formsdata.c \
 +		dwarf_srclang.c dwarf_formflag.c dwarf_diecu.c \
-+		dwarf_bytesize.c dwarf_bitsize.c dwarf_peel_type.c
++		dwarf_bytesize.c dwarf_bitsize.c dwarf_peel_type.c \
++		dwarf_default_lower_bound.c
 +
  if MAINTAINER_MODE
  BUILT_SOURCES = $(srcdir)/known-dwarf.h
  MAINTAINERCLEANFILES = $(srcdir)/known-dwarf.h
-@@ -101,10 +116,13 @@ endif
+@@ -101,9 +117,12 @@ endif
  
  libdw_pic_a_SOURCES =
  am_libdw_pic_a_OBJECTS = $(libdw_a_SOURCES:.c=.os)
 +am_libdw_static_pic_a_OBJECTS = $(libdw_static_pic_a_SOURCES:.c=.os)
  
- libdw_so_SOURCES =
- libdw.so$(EXEEXT): $(srcdir)/libdw.map libdw_pic.a ../libdwelf/libdwelf_pic.a \
- 	  ../libdwfl/libdwfl_pic.a ../libebl/libebl.a \
+ libdw_so_LIBS = libdw_pic.a ../libdwelf/libdwelf_pic.a \
+-	  ../libdwfl/libdwfl_pic.a ../libebl/libebl.a
++	  ../libdwfl/libdwfl_pic.a ../libebl/libebl.a \
 +	  ../backends/libebl_static_pic.a \
-+	  ../libcpu/libcpu_static_pic.a \
- 	  ../libelf/libelf.so
- # The rpath is necessary for libebl because its $ORIGIN use will
- # not fly in a setuid executable that links in libdw.
++	  ../libcpu/libcpu_static_pic.a
+ libdw_so_DEPS = ../lib/libeu.a ../libelf/libelf.so
+ libdw_so_LDLIBS = $(libdw_so_DEPS) -ldl -lz $(argp_LDADD) $(zip_LIBS)
+ libdw_so_SOURCES =
 diff --git a/libdwelf/Makefile.am b/libdwelf/Makefile.am
 index 7ca767a..b526b7c 100644
 --- a/libdwelf/Makefile.am
@@ -174,12 +176,12 @@ index 89ca92e..d9d13b2 100644
  		    dwfl_module.c dwfl_report_elf.c relocate.c \
  		    dwfl_module_build_id.c dwfl_module_report_build_id.c \
 diff --git a/libebl/Makefile.am b/libebl/Makefile.am
-index 6f945eb..7034b61 100644
+index 2491df8..6d5b07f 100644
 --- a/libebl/Makefile.am
 +++ b/libebl/Makefile.am
-@@ -55,6 +55,7 @@ gen_SOURCES = eblopenbackend.c eblclosebackend.c \
- 	      eblstother.c eblinitreg.c ebldwarftoregno.c eblnormalizepc.c \
- 	      eblunwind.c eblresolvesym.c eblcheckreloctargettype.c
+@@ -56,6 +56,7 @@ gen_SOURCES = eblopenbackend.c eblclosebackend.c \
+ 	      eblunwind.c eblresolvesym.c eblcheckreloctargettype.c \
+ 	      ebl_data_marker_symbol.c
  
 +libebl_a_CFLAGS = -fvisibility=hidden $(AM_CFLAGS)
  libebl_a_SOURCES = $(gen_SOURCES)
@@ -201,7 +203,7 @@ index 67fbdfe..501e5c7 100644
        free (ebl);
      }
 diff --git a/libebl/eblopenbackend.c b/libebl/eblopenbackend.c
-index f3a65cf..8630053 100644
+index 1f81477..1728115 100644
 --- a/libebl/eblopenbackend.c
 +++ b/libebl/eblopenbackend.c
 @@ -42,6 +42,14 @@
@@ -386,7 +388,7 @@ index f3a65cf..8630053 100644
  };
  #define nmachines (sizeof (machines) / sizeof (machines[0]))
  
-@@ -315,46 +323,17 @@ openbackend (Elf *elf, const char *emulation, GElf_Half machine)
+@@ -317,46 +325,17 @@ openbackend (Elf *elf, const char *emulation, GElf_Half machine)
  #endif
  #define ORIGINDIR "$ORIGIN/../$LIB/" LIBEBL_SUBDIR "/"
  
@@ -436,7 +438,7 @@ index f3a65cf..8630053 100644
  		result->elf = elf;
  
  		/* A few entries are mandatory.  */
-@@ -363,9 +342,6 @@ openbackend (Elf *elf, const char *emulation, GElf_Half machine)
+@@ -365,9 +344,6 @@ openbackend (Elf *elf, const char *emulation, GElf_Half machine)
  
  		return result;
  	      }
@@ -447,7 +449,7 @@ index f3a65cf..8630053 100644
  
  	/* We cannot find a DSO but the emulation/machine ID matches.
 diff --git a/libelf/Makefile.am b/libelf/Makefile.am
-index 167a832..0c74e3f 100644
+index 88c1edd..f873ed0 100644
 --- a/libelf/Makefile.am
 +++ b/libelf/Makefile.am
 @@ -41,6 +41,7 @@ include_HEADERS = libelf.h gelf.h nlist.h
@@ -494,20 +496,19 @@ index 2b1c0dc..657b21a 100644
  strings_LDADD = $(libelf) $(libeu) $(argp_LDADD)
  ar_LDADD = libar.a $(libelf) $(libeu) $(argp_LDADD)
 diff --git a/tests/Makefile.am b/tests/Makefile.am
-index 3a12fe3..d17ffd4 100644
+index 3735084..483f387 100644
 --- a/tests/Makefile.am
 +++ b/tests/Makefile.am
-@@ -80,8 +80,8 @@ TESTS = run-arextract.sh run-arsymtest.sh newfile test-nlist \
+@@ -80,7 +80,7 @@ TESTS = run-arextract.sh run-arsymtest.sh newfile test-nlist \
  	newscn run-strip-test.sh run-strip-test2.sh \
  	run-strip-test3.sh run-strip-test4.sh run-strip-test5.sh \
  	run-strip-test6.sh run-strip-test7.sh run-strip-test8.sh \
 -	run-strip-test9.sh run-strip-test10.sh run-strip-test11.sh \
 +	run-strip-test9.sh run-strip-test10.sh \
- 	run-strip-nothing.sh \
+ 	run-strip-nothing.sh run-strip-g.sh \
  	run-strip-groups.sh run-strip-reloc.sh run-strip-strmerge.sh \
- 	run-strip-nobitsalign.sh \
- 	run-unstrip-test.sh run-unstrip-test2.sh run-unstrip-test3.sh \
-@@ -402,7 +402,8 @@ libdw = ../libdw/libdw.so
+ 	run-strip-nobitsalign.sh run-strip-remove-keep.sh \
+@@ -404,7 +404,8 @@ libdw = ../libdw/libdw.so
  libelf = ../libelf/libelf.so
  libasm = ../libasm/libasm.so
  endif
@@ -517,7 +518,7 @@ index 3a12fe3..d17ffd4 100644
  libeu = ../lib/libeu.a
  endif !STANDALONE
  
-@@ -430,6 +431,7 @@ get_lines_LDADD = $(libdw) $(libelf)
+@@ -432,6 +433,7 @@ get_lines_LDADD = $(libdw) $(libelf)
  get_files_LDADD = $(libdw) $(libelf)
  get_aranges_LDADD = $(libdw) $(libelf)
  allfcts_LDADD = $(libdw) $(libelf)
@@ -526,7 +527,7 @@ index 3a12fe3..d17ffd4 100644
  addrscopes_LDADD = $(libdw) $(argp_LDADD)
  funcscopes_LDADD = $(libdw) $(argp_LDADD)
 diff --git a/tests/run-addrcfi.sh b/tests/run-addrcfi.sh
-index c864eea..2691091 100755
+index 376a6dc..7fc46e5 100755
 --- a/tests/run-addrcfi.sh
 +++ b/tests/run-addrcfi.sh
 @@ -3521,82 +3521,6 @@ testrun_compare ${abs_builddir}/addrcfi -e testfiles390x 0x0000000080000510 <<\E
@@ -613,7 +614,7 @@ index c864eea..2691091 100755
  # Same as arm, 390 and ppc above.
  # Note missing coverage in .eh_frame.
 diff --git a/tests/run-allregs.sh b/tests/run-allregs.sh
-index d82f37e..a56e612 100755
+index 7ddd452..0d2eb52 100755
 --- a/tests/run-allregs.sh
 +++ b/tests/run-allregs.sh
 @@ -2344,387 +2344,6 @@ control registers:
@@ -1295,6 +1296,42 @@ index 86171c4..382ea14 100755
 -EOF
 -
  exit 0
+diff --git a/tests/run-strip-g.sh b/tests/run-strip-g.sh
+index 1303819..8024aa5 100755
+--- a/tests/run-strip-g.sh
++++ b/tests/run-strip-g.sh
+@@ -49,31 +49,6 @@ if test $status -ne 1; then
+   exit 1
+ fi
+ 
+-# arm (with data marker in .debug_frame). See tests/run-addrcfi.sh
+-testfiles testfilearm
+-
+-echo arm strip -g to file with debug file
+-testrun ${abs_top_builddir}/src/strip -g -o strip.out -f debug.out testfilearm ||
+-  { echo "*** failed to strip -g -o strip.out -f debug.out a.out"; exit -1; }
+-
+-status=0
+-testrun ${abs_top_builddir}/src/readelf -S strip.out > readelf.out
+-grep SYMTAB readelf.out || status=$?
+-echo $status
+-if test $status -ne 0; then
+-  echo no symtab found in strip.out
+-  exit 1
+-fi
+-
+-status=0
+-testrun ${abs_top_builddir}/src/readelf -S debug.out > readelf.out
+-grep SYMTAB readelf.out || status=$?
+-echo $status
+-if test $status -ne 1; then
+-  echo symtab found in debug.out
+-  exit 1
+-fi
+-
+ # aarch64 (with data marker in .debug_frame). See tests/run-addrcfi.sh
+ testfiles testfileaarch64
+ 
 diff --git a/tests/run-strip-reloc.sh b/tests/run-strip-reloc.sh
 index e587eab..5c847a4 100755
 --- a/tests/run-strip-reloc.sh
